[package]
name = "distraction-oni"
version = "0.0.1"
authors = ["Mateusz Cegiełka <mateusz@cegla.net>"]
edition = "2018"
description = "Integrated distraction manager to regain control of your computer and Internet use"
repository = "https://github.com/pustaczek/distraction-oni"
license = "MPL-2.0"
keywords = ["productivity"]
default-run = "distraction-oni"

[dependencies]
chrono = "0.4"
json = "0.12"
webext = { path = "webext" }
#x11 = { version = "2.18", features = ["xlib"] }

[[bin]]
name = "distraction-oni-webext"
path = "src/main-webext.rs"

[workspace]
members = [
    ".",
    "webext",
]
