[package]
name = "distraction-oni"
version = "0.0.1"
authors = ["Mateusz Cegiełka <mateusz@cegla.net>"]
edition = "2018"
description = "Integrated distraction manager to regain control of your computer and Internet use"
repository = "https://github.com/pustaczek/distraction-oni"
license = "MPL-2.0"
keywords = ["productivity"]
default-run = "distraction-oni"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
x11 = { version = "2.18", features = ["xlib"] }
