name: Continuous Integration
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  CARGO_TERM_COLOR: always
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: sudo apt-get install libdbus-1-dev
    - name: Build
      run: cargo build --all
    - name: Test
      run: cargo test --all
  Format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt --all -- --check
  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: sudo apt-get install libdbus-1-dev
    - name: Lint
      run: cargo clippy --all -- -D warnings
  Coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust nightly
      run: rustup default nightly
    - name: Install system dependencies
      run: sudo apt-get install libdbus-1-dev llvm
    - name: Test
      run: RUSTFLAGS="-Z instrument-coverage" LLVM_PROFILE_FILE="json5format.profraw" cargo test --tests
    - name: Generate coverage report (merge .profraw files)
      run: llvm-profdata merge -sparse json5format.profraw -o json5format.profdata
    - name: Generate coverage report (render Codecov-compatible output)
      run: llvm-cov show `ls target/debug/deps/vaxtify-* | head -n1` -instr-profile=json5format.profdata --ignore-filename-regex='/.cargo/registry|/rustc/' > coverage.txt
    - name: Send coverage report
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
